spring:
  application:
    name: edgeinsight-platform
  datasource:
    url: jdbc:mysql://localhost:3306/edgeinsight?useSSL=false&serverTimezone=UTC
    username: root
    password: 200472
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

security:
  public-paths:
    - POST:/api/v1/auth/login

logging:
  level:
    com.huidou.edgeinsight: DEBUG
    org.springframework.security: DEBUG

